server:
  port : 8081

spring :
  datasource:
    #driver-class-name: oracle.jdbc.OracleDriver
    #url: jdbc:oracle:thin:@3.35.176.97:1521/xe
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:oracle:thin:@3.35.176.97:1521/xe

    username: root
    password: 1234

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

mybatis:
  configuration:
    multiple-result-sets-enabled: false
    lazyLoadingEnabled: true
    aggressiveLazyLoading: false
    jdbc-type-for-null: varchar
    default-fetch-size: 500

  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.uos.cinemaseoul/**/**/

